portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import jobs.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', jobs.views.home, name='home')
]   

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models
from datetime import date

class Job(models.Model):
    image = models.ImageField(upload_to='static/images/')
    job_title = models.CharField(max_length=100, default='title')
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(default=date.today)
    current_job = models.BooleanField(default=False)
    company_name = models.CharField(max_length=100, default='company')
    summary = models.TextField(default='summary')
    def __str__(self):
        return '{self.job_title}, {self.company_name}'.format(self=self)

class Highlights(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    highlights = models.CharField(max_length=300, default='highlight')
    def __str__(self):
        return self.highlights

class Bio(models.Model):
    bio = models.TextField(default="bio")
    def __str__(self):
        return self.bio

class BioPic(models.Model):
    image = models.ImageField(upload_to='static/images/')

class Certifications(models.Model):
    cert_title = models.CharField(max_length=200)
    cert_company = models.CharField(max_length=200)
    cert_badge = models.TextField(default='')
    def __str__(self):
        return self.cert_title

class BackgroundImage(models.Model):
    image = models.ImageField(upload_to='static/images')

class Education(models.Model):
    school = models.CharField(max_length=100)
    degree = models.CharField(max_length=100)
    def __str__(self):
        return self.school
    


    
    

jobs/views.py
from django.shortcuts import render
from .models import Job, Bio, BioPic, BackgroundImage, Certifications, Education

def home(request):
    jobs = Job.objects.order_by('-start_date')
    bio = Bio.objects
    bio_pic = BioPic.objects
    background = BackgroundImage.objects
    certs = Certifications.objects
    education = Education.objects
    return render(request, 'jobs/home.html', {'jobs': jobs, 'bio': bio,
                             'bio_pic': bio_pic, 'background': background, 
                             'certs': certs, 'education':education})

jobs/templates/jobs/home.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Anthony Russo</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body>
    <header>
</header>
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1>Anthony Russo</h1>
      <p class="lead text-muted">{{ bio.first }}</p>
      <img src="{{ bio_pic.first.image.url }}"height=300 style='padding: 10px; clip-path: circle(120px at center);'>
      <p>
        <a href="mailto:anthony.russo.7@outlook.com" class="btn btn-primary my-2">Email me</a>
      </p>
    </div>
    <div class="container">
        <h2>Certifications</h2>
        {% autoescape off %}
        {% for b in certs.all %}
            {{ b.cert_badge }}
        {% endfor %}
        {% endautoescape %}
        <ul class="list-group list-group-horizontal">
        </ul>
    </div>
    <div class="container" style='padding-top: 10px;'>
        <h2>Education</h2>
        <ul class="list-group list-group-horizontal">
        {% for e in education.all %}
            <li class="list-group-item">{{ e.degree }}<br><br><strong>{{ e.school }}</strong></li>
        {% endfor %}
        </ul>
    </div>
  <div class="album py-5 bg-light">
    <div class="container" style='padding-bottom: 25px;'>
      <h2>Professional Experience</h2>
    </div>
    <div class="container text-left">
      <div class="row">
        {% for e in jobs %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="{{ e.image.url }}">
            <div class="card-body">
                <h3>{{ e.job_title }}</h3>
                <p class="card-text">{{ e.summary }}</p>
                {% comment %} <p class="card-text">
                {% for highlights in e.highlights_set.all %}
                        <ul>
                            <li>{{ highlights }}</li>
                        </ul>
                    {% endfor %}
                </p> {% endcomment %}
                <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{ e.start_date }} - 
                {% if e.current_job is True %}
                    Present
                {% else %}
                    {{ e.end_date }}
                {% endif %}
                </small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  </section>

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
  </div>
</footer>
<script src="{% static 'jquery-3.5.1.min.js' %}"> </script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'popper.min.js' %}"></script
</html>